### ISSUE TITLE
There are duplicate hosts with the following values

### ISSUE THREAD

**Issue by lello1978** [jrossi227/ApacheGUI#30]
If you configure a virtualhost with Servername in 443 port this error appear:
There was an error processing the Virtual Hosts.
There are duplicate hosts with the following values:

File: /etc/apache2/sites-available/cms.pasello.com-ssl.conf Line: 1
ServerName: cms.pasello.com:443
NetworkInfo: 192.168.254.104:443

File: /etc/apache2/sites-available/cms.pasello.com-ssl.conf Line: 1
ServerName: cms.pasello.com:443
NetworkInfo: 192.168.254.104:443

You must fix the configuration error before using the Virtual Host functionality

**Comment by jrossi227** [comment]
Are you including the file /etc/apache2/sites-available/cms.pasello.com-ssl.conf twice in your apache configuration?

The error appears when there are two virtual hosts with the same host, port and ServerName. Since the error reports that the overlap happens in the same file and line number it leads me to believe the file has been included multiple times in the apache configuration.

**Comment by lello1978** [comment]
pre {display: block;font-family: Helvetica Neue, Helvetica, Arial, sans-serif;white-space: pre-wrap;margin: 1em 0;}Ill check asap....tomorrow i wiil respond you  thanks

Inviato da IBM VerseJonathan Rossi --- Re: [ApacheGUI] There are duplicate hosts with the following values (#30) --- Da:"Jonathan Rossi" <notifications@github.com>A:"jrossi227/ApacheGUI" <ApacheGUI@noreply.github.com>Cc:"lello1978" <marcello.modica@logconsulting.it>Data:mer, 14/ott/2015 20:51Oggetto:Re: [ApacheGUI] There are duplicate hosts with the following values (#30)Are you including the file /etc/apache2/sites-available/cms.pasello.com-ssl.conf twice in your apache configuration?

The error appears when there are two virtual hosts with the same host, port and ServerName. Since the error reports that the overlap happens in the same file and line number it leads me to believe the file has been included multiple times in the apache configuration.

**Comment by lello1978** [comment]
In ubuntu 14.04 (i think) at the end of file apache2.conf, may encounter this lines:
# Include generic snippets of statements
IncludeOptional conf-enabled/*.conf

# Include the virtual host configurations:
IncludeOptional sites-enabled/*.conf

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet


But i f you use add Vhost function in apacheGui, it add Include directive too!
Thanks

**Comment by jrossi227** [comment]
Can you please supply the values that you use to add a Virtual Host in the Apache GUI Virtual hosts interface. Did you specify a new file and use a file that woulld otherwise be included by the wildcard includes you specified?

If this is the case manually remove the Include directive from apache2.conf that is generated for the file you created.

**Comment by jrossi227** [comment]
Closing as a non issue, this is just including a file multiple times.
